# Generated by Django 3.2.8 on 2021-10-21 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, verbose_name='ID пользователя')),
                ('text', models.CharField(blank=True, max_length=300, null=True, verbose_name='Вопрос ')),
                ('answer', models.TextField(blank=True, max_length=300, null=True, verbose_name='Ответ')),
                ('type', models.CharField(choices=[('TXT', 'Текст'), ('UNO', 'Один вариант'), ('SOM', 'Несколько')], default='TXT', max_length=3, verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('start_date', models.DateField(default=datetime.date.today, editable=False, verbose_name='Дата старта опроса')),
                ('end_date', models.DateField(verbose_name='Дата окончания опроса')),
                ('questions', models.ManyToManyField(related_name='questions', to='questionnaire.Questions')),
            ],
            options={
                'verbose_name': 'Опросник',
                'verbose_name_plural': 'Опросники',
            },
        ),
    ]
